name: Buzz Alert
on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 3 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  buzz-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --prefix . --package-lock-file=package-lock.buzz.json --package=package.buzz.json
      - run: node buzz-alert.js
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          STATS_BASE_URL: https://www.japan-stats.com
